name: "Example workflow: Build an artifact and perform tests"

# This workflow will:
# - Build a compmlete artifact (downloading all dependencies, and running any
#   front-end build commands).
# - Perform a number of tests against the codebase, including Composer security
#   checks, PHP static analysis, and PHPUnit tests.
# - Commit the complete artifact and push it to the remote repository, if the
#   'Build' label is applied to the pull request.
#
# It will run when a pull request into the main branch is created, and the
# checks can be used to restrict whether a PR can be merged or not.

on:
  # Whenever a pull request is opened or changed. This workflow will run if new
  # commits are pushed to this branch.
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

defaults:
  run:
    shell: bash

# Cancel out of date jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Download dependencies to build a project using a Composer lockfile.
  composer-build:
    name: 'Build: Composer dependencies.'
    uses: thisisgain/.github/.github/workflows/01-build-composer.yml@main
    with:
      container: registry.gitlab.com/freelygive/docker/drupal-php-node:p8.3-cli-n20

  # Test for any security updates required.
  composer-security:
    name: 'Test: Composer security.'
    needs: [composer-build]
    uses: thisisgain/.github/.github/workflows/02-test-composer-security.yml@main
    with:
      container: registry.gitlab.com/freelygive/docker/drupal-php-node:p8.3-cli-n20

  # Perform PHP static analysis and code linting.
  php-analysis:
    name: 'Test: PHP static analysis.'
    needs: [composer-build]
    uses: thisisgain/.github/.github/workflows/02-test-php-analysis.yml@main
    with:
      container: registry.gitlab.com/freelygive/docker/drupal-php-node:p8.3-cli-n20
      phpstan: true

  # Run PHPUnit tests.
  phpunit:
    name: 'Test: PHPUnit automated tests.'
    needs: [composer-build]
    uses: thisisgain/.github/.github/workflows/02-test-php-phpunit.yml@main
    with:
      container: registry.gitlab.com/freelygive/docker/drupal-php-node:p8.3-cli-n20

  push-code:
    name: 'Deploy: push artifact to repository.'
    # Only push if all checks have passed.
    needs: [composer-security, php-analysis, phpunit]
    # Only push if the "Build" label has been applied.
    if: contains(github.event.pull_request.labels.*.name, 'Build')
    uses: thisisgain/.github/.github/workflows/03-deploy-artifact.yml@main
    with:
      container: registry.gitlab.com/freelygive/docker/drupal-php-node:p8.3-cli-n20
      git_name: GAIN Automation
      git_email: geeks+client.gha@thisisgain.com
      source_key: composer
      add_files_defaults: false
      add_files: >-
        vendor/
        docroot/.htaccess
        docroot/index.php
        docroot/autoload.php
        docroot/*/
      remove_files: >-
        tests/
        docroot/themes/custom/custom_theme/node_modules/
    secrets:
      REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
      REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}
      SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
      KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      GITHUB_READ_TOKEN: ${{ secrets.GITHUB_READ_TOKEN }}
