# Name: Run Cypress tests in a container.
# Type: Action.
# Use: Runs Cypress tests within a container, to allow front-end browser tests.

name: Run Cypress tests
description: 'Run Cypress tests in a container.'

inputs:
  hosts_entry:
    description: 'Entry for the hosts file.'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
