# Name: Run PHP static analysis.
# Type: Test.
# Use: Run Drupal-focused PHP static analysis checks, including PHPCS, PHPStan,
#      GrumPHP, and Drupal Check.

name: Run PHP static analysis.

on:
  workflow_call:
    inputs:
      phpcs:
        description: 'Whether to run PHP Coding Standards checks.'
        type: boolean
        default: true
      container:
        description: 'The Docker image to use.'
        type: string
        required: true
      source_key:
        description: 'The source cache key suffix, or empty to perform a clean checkout.'
        type: string
        default: 'composer'
      directory:
        description: 'The directory in which to run commands.'
        type: string
        default: './'
      phpstan:
        description: 'Whether to run PHPStan checks.'
        type: boolean
        default: false
      grumphp:
        description: 'Whether to run GrumPHP checks.'
        type: boolean
        default: false
      drupal_check:
        description: 'Whether to run Drupal Check.'
        type: boolean
        default: false
      drupal_check_directories:
        description: 'Directories for the Drupal Check scan.'
        type: string
        default: ''
      drupal_check_level:
        description: 'Directories for the Drupal Check scan.'
        type: string
        default: 'a'

defaults:
  run:
    shell: bash

jobs:
  phpcs:
    name: 'PHP Coding Standards'
    if: inputs.phpcs
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Restore build from a previous step.
        uses: actions/cache/restore@v5
        id: restore-build
        with:
          path: ./*
          # We are only interested in a direct hit.
          key: build-${{ github.sha }}-${{ inputs.source_key }}

      - name: Abort if we have a source build cache miss.
        run: exit 1
        if: steps.restore-build.outputs.cache-hit != 'true'

      - name: Abort if PHPCS isn't installed.
        run: test -f ./vendor/bin/phpcs || exit 1

      - name: Run PHPCS.
        run: |
          cd ${{ inputs.directory }}
          ./vendor/bin/phpcs

  phpstan:
    name: 'PHPStan'
    if: inputs.phpstan
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Restore build from a previous step.
        uses: actions/cache/restore@v5
        id: restore-build
        with:
          path: ./*
          # We are only interested in a direct hit.
          key: build-${{ github.sha }}-${{ inputs.source_key }}

      - name: Abort if we have a source build cache miss.
        run: exit 1
        if: steps.restore-build.outputs.cache-hit != 'true'

      - name: Abort if PHPStan isn't installed.
        run: test -f ./vendor/bin/phpstan || exit 1

      - name: Run PHPStan.
        run: |
          cd ${{ inputs.directory }}
          ./vendor/bin/phpstan

  grumphp:
    name: 'GrumPHP coding standards check'
    if: inputs.grumphp != ''
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Restore build from a previous step.
        uses: actions/cache/restore@v5
        id: restore-build
        with:
          path: ./*
          # We are only interested in a direct hit.
          key: build-${{ github.sha }}-${{ inputs.source_key }}

      - name: Abort if we have a source build cache miss.
        run: exit 1
        if: steps.restore-build.outputs.cache-hit != 'true'

      - name: Abort if GrumPHP isn't installed.
        run: test -f ./vendor/bin/grumphp || exit 1

      - name: Run GrumPHP checks.
        run: |
          cd ${{ inputs.directory }}
          ./vendor/bin/grumphp run

  drupal-check:
    name: 'Drupal Check Analysis'
    if: inputs.drupal_check
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Restore build from a previous step.
        uses: actions/cache/restore@v5
        id: restore-build
        with:
          path: ./*
          # We are only interested in a direct hit.
          key: build-${{ github.sha }}-${{ inputs.source_key }}

      - name: Abort if we have a source build cache miss.
        run: exit 1
        if: steps.restore-build.outputs.cache-hit != 'true'

      - name: Abort if Drupal Check isn't installed.
        run: test -f ./vendor/bin/drupal-check || exit 1

      - name: Run Drupal Check.
        run: |
          cd ${{ inputs.directory }}
          ./vendor/bin/drupal-check -${{ inputs.drupal_check_level }} ${{ inputs.drupal_check }}
