# Name: Deploy an artifact using Git.
# Type: Deploy.
# Use: Deploy a fully-built artifact to a remote environment. This could be a
#      tag or a branch.

name: Push a build artifact to a Git remote.

on:
  workflow_call:
    inputs:
      target_ref:
        description: 'The target ref to push to, e.g. refs/heads/BRANCH or refs/tags/TAG.'
        type: string
        required: false
    secrets:
      REMOTE_REPO:
        description: 'The remote repository URL.'
        required: true
      REMOTE_SSH_KEY:
        description: 'Private SSH key authorised to push to the remote repository.'
        required: true
      SSH_CONFIG:
        description: 'SSH configuration. Can be an empty secret, or not included.'
      KNOWN_HOSTS:
        description: 'SSH known hosts. Set using `ssh-keygen` command.'
        required: true

defaults:
  run:
    shell: bash

jobs:
  push-code:
    name: 'Push code to remote repository'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          # Ensure PRs check out the right commit.
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          # Perform a full checkout to prevent orphaned commits.
          fetch-depth: 0

      - name: Set up the SSH key and configuration
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Add the Git remote
        run: git remote add target ${{ secrets.REMOTE_REPO }}

      - name: Push code
        run: git push target HEAD:${{ inputs.target_ref || (github.event.pull_request.head.ref && format('refs/heads/{0}', github.event.pull_request.head.ref) ) || github.ref }} --force
